server:
  port: 80
  shutdown: graceful
spring:
  application:
    name: qt-bus
  threads:
    virtual:
      enabled: true
  profiles:
    active: ${env:prod}
  mvc:
    async:
      request-timeout: 600000